name: cd

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: pacman --noconfirm -Sy inkscape graphviz uv python git

    - name: Set up Holocron
      run: uv tool install "$HOLOCRON_PYTHON_PACKAGE"
      env:
        HOLOCRON_PYTHON_PACKAGE: git+https://github.com/ikalnytskyi/holocron.git@master

    - name: Run Holocron
      run: uv tool run -- holocron run compile

    - name: Upload GitHub Pages archive
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site/

  publish:
    needs: build
    runs-on: ubuntu-24.04

    permissions:
      pages: write
      id-token: write

    environment:
      name: kalnytskyi.com
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
