name: cd

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Inkscape
      run: sudo apt-get update && sudo apt-get install inkscape

    - name: Set up Graphviz
      run: |
        curl -L -o "${{ runner.temp }}/graphviz.deb" "$GRAPHVIZ_DEB_URL"
        sudo apt-get install "${{ runner.temp }}/graphviz.deb"
      env:
        GRAPHVIZ_DEB_URL: https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/12.2.1/ubuntu_24.04_graphviz-12.2.1-cmake.deb

    - name: Set up Holocron
      run: uv tool install "$HOLOCRON_PYTHON_PACKAGE"
      env:
        HOLOCRON_PYTHON_PACKAGE: git+https://github.com/ikalnytskyi/holocron.git@master

    - name: Run Holocron
      run: holocron run compile

    - name: Upload GitHub Pages archive
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site/

  publish:
    needs: build
    runs-on: ubuntu-24.04

    permissions:
      pages: write
      id-token: write

    environment:
      name: kalnytskyi.com
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
