name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: archlinux:latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: pacman --noconfirm -Sy inkscape graphviz uv python git

    - name: Set up Holocron
      run: uv tool install "$HOLOCRON_PYTHON_PACKAGE"
      env:
        HOLOCRON_PYTHON_PACKAGE: git+https://github.com/ikalnytskyi/holocron.git@master

    - name: Run Holocron
      run: uv tool run -- holocron run compile
